In [1]:
import numpy as np

arr1 = np.array ([1,2,3,4,5])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [1 2 3]]


In [2]:
arr1 = arr1+10 
print(arr1)

arr2 *= 2

print(arr2)

[11 12 13 14 15]
[[2 4 6]
 [2 4 6]]


In [3]:
print(arr1[2])
print(arr1[2:4])
print(arr2[0,2])
print(arr2[0:2,2]) #pega os valores da coluna 2

13
[13 14]
6
[6 6]


In [4]:
seno_array = np.sin(arr1)
log_arr2 = np.log(arr2)

print(seno_array)
print(log_arr2)

[-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
[[0.69314718 1.38629436 1.79175947]
 [0.69314718 1.38629436 1.79175947]]
