In [ ]:
import numpy as np

arr1 = np.array ([1,2,3,4,5])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1)
print(arr2)

In [ ]:
arr1 = arr1+10 
print(arr1)

arr2 *= 2

print(arr2)

In [ ]:
print(arr1[2])
print(arr1[2:4])
print(arr2[0,2])
print(arr2[0:2,2]) #pega os valores da coluna 2

In [16]:
seno_array = np.sin(arr1)
log_arr2 = np.log(arr2)

print(seno_array)
print(log_arr2)

[ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]
[[1.38629436 2.07944154 2.48490665]
 [1.38629436 2.07944154 2.48490665]]
