In [1]:
import numpy as np

arr1 = np.array([ 1, 2, 3, 4, 5])
arr2 = np.array([11,12,13,14,15])

print("Numpy brodcasting")

soma_broadcast = arr1 + arr2
mult_broadcast = arr1 * arr2
print(soma_broadcast)
print(mult_broadcast)

Numpy brodcasting
[12 14 16 18 20]
[11 24 39 56 75]


In [2]:
arr3 = np.array([[0,1,2],[3,4,5],[9,10,11]])
print("Array original")
print(arr3)
print("Linhas impares:")
print(arr3[1::2,:]) #começa pela linh 1 e pula de 2 em 2
print("Linhas pares:")
print(arr3[0::2,:])

print("coluna impares")
print(arr3[:,1::2])

print("coluna pares")
print(arr3[:,0::2])

Array original
[[ 0  1  2]
 [ 3  4  5]
 [ 9 10 11]]
Linhas impares:
[[3 4 5]]
Linhas pares:
[[ 0  1  2]
 [ 9 10 11]]
coluna impares
[[ 1]
 [ 4]
 [10]]
coluna pares
[[ 0  2]
 [ 3  5]
 [ 9 11]]


In [ ]:
print("Criando np array inicaod com zeros")
arr4= np.zeros ((3,4))
print(arr4)
print("Criando np array inicaod com 1s")
arr4= np.ones ((3,3,4),dtype= np.int16)
print(arr4)
print(arr4.dtype.name) #para mostrar o tipo

In [ ]:
print("Exemplo numpy multidimencional com valores random")
arr5 = np.random.randint(10, size=6)
arr6 = np.random.randint(10, size=(3,4))
arr7 = np.random.randint(10, size=(3,4,5))

print(" === Arr5 ===")
print(arr5)
print(" === Arr6 ===")
print(arr6)
print(" === Arr7 ===")
print(arr7)


In [107]:
print("Convertendo tipo do array")
arr7 = np.array(arr7, dtype=float)
print(arr7/1.25)

Convertendo tipo do array
[[[4.  1.6 7.2 1.6 4.8]
  [5.6 1.6 0.8 5.6 5.6]
  [0.8 7.2 0.8 2.4 4. ]
  [4.  0.  3.2 4.8 1.6]]

 [[4.8 0.8 0.  1.6 1.6]
  [7.2 0.8 5.6 7.2 3.2]
  [0.8 7.2 5.6 1.6 7.2]
  [5.6 6.4 0.8 0.  0. ]]

 [[1.6 0.  0.8 4.8 4.8]
  [5.6 5.6 4.  5.6 2.4]
  [2.4 4.  5.6 4.  4. ]
  [5.6 0.8 0.8 3.2 7.2]]]
