#### arrange

In [8]:
import numpy as np

arr1 = np.arange(0,10,dtype = int) # or arange(10)

print(arr1)

arr2 = np.arange(2,11,2)
print(arr2)

arr3 = np.arange(0,1.2,0.1, dtype = float)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


#### reshape

In [9]:
print("alterando forma de 1x10 por 2x5")
arr4 = np.reshape(arr1, (2,5), 'C')
print(arr4)
arr4 = np.reshape(arr1, (2,5), 'F')
print(arr4)

alterando forma de 1x10 por 2x5
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
